### ISSUE TITLE
reactive-relations is no longer under development

### ISSUE THREAD

**Issue by dandv** [emmerge/graviton#10]
The lead paragraph reads,

> Use other packages to handle validation (meteor-simple-schema) hooks (meteor-collection-hooks) and relational pub/sub (reactive-relations)

**Comment by mhwheeler** [comment]
I've removed the reference to `reactive-relations` and substituted an active relational pub/sub package `cottz:publish-relations`. Thanks so much for your work on informing our community about "Prior Art", Dan!
