### ISSUE TITLE
Extend Graviton model with schema

### ISSUE THREAD

**Issue by chongwang87** [emmerge/graviton#8]
Want to know is there anyway to define schema for Graviton model like aldeed:simple-schema?

Or anyway to extend Graviton model with aldeed:simple-schema?

If possible, please give example how to do it. 

Thanks.

**Comment by michalCapo** [comment]
* your dependencies
```
# model validations
meteor add aldeed:simple-schema
meteor add aldeed:collection2

# model relations
meteor add emmerge:graviton
```

* your model defines like this:
```
RouteSchema = new SimpleSchema({
    carId: {
        type: String
    },
    name: {
        type: String
    }
});

RouteModel = Graviton.Model.extend({
    belongsTo: {
        car: {
            collectionName: 'car',
            foreignKey: 'carId'
        }
    }, {
});

Route = Graviton.define('route', {
    modelCls: RouteModel
});

Route.attachSchema(RouteSchema);
```

**Comment by mhwheeler** [comment]
We do something very similar to what @michalCapo writes above (but without collection2). Does this example help @chongwang87. I'm going to close this. Please reopen if you still have questions.
